### ISSUE TITLE
Implement a service responsible for event aggregation

### ISSUE THREAD

**Issue by superbobry** [criteo/tf-yarn#10]
Currently, event aggregation assumes that Skein K/V store will deliver the events even if the container terminates abnormally. I am not sure if this can be relied on. Alternatively, we can implement a variant of what @jcrist was suggesting in jcrist/skein#67:

> [...] an additional service (rather than running on the edge node) in your application to keep track of this state (or push it into one of your existing services). If designed right, this service should never exceed the memory limit (lightweight, don't do work here), and can monitor and report back on the state of the application until some stopping condition (all other containers have completed) before exiting itself.

**Comment by jcrist** [comment]
Watchers watching the K/V store should see all events that the application master received, as long as the application master doesn't terminate abnormally (e.g. master killed by YARN or a fatal error in the application master). If the application master shuts down due to application failure, I *think* all events should still be sent before shutdown concludes (or at least they should be).

I do recommend having some sort of monitoring process you've implemented though, as I believe that will possibly be simpler to implement than shoving more control and state into the skein k/v store.
