### ISSUE TITLE
Change ``run_on_yarn`` to accept a zipped environment

### ISSUE THREAD

**Issue by superbobry** [criteo/tf-yarn#16]
Automatic building of the Conda environment in `run_on_yarn` might look convenient, but in practice, it turns out to be a liability. Specifically, 

* it introduces a runtime dependency on Conda (which should be installed on the edge node),
* it does not allow to use non-Conda environments, e.g. pure virtualenv or PEX,
* it limits the environment to the host OS type, i.e. it is impossible to submit from a non-Linux machine,
* it slows down the execution, 
* it pollutes the tmpdir with cryptic environment directories/archives.

The only reason tf-yarn has this logic is the fact that TensorFlow comes in two packages: CPU-only and CPU/GPU which is dynamically linked with CUDA. There is [work underway](https://github.com/tensorflow/tensorflow/issues/16184) to make CUDA libraries dynamically loadable and remove the unnecessary dichotomy. Once this is done, `run_on_yarn` can be safely migrated to accept a zipped environment to be used on both CPU-only and GPU-enabled nodes.

**Comment by jcrist** [comment]
For `dask-yarn` we've found it useful to have the user pre-package their environment, or install it already on every node. The `environment` kwarg takes any of the following (from [the docs](https://dask-yarn.readthedocs.io/en/latest/environments.html)):

> - The path to an archived environment (either conda or virtual environments)
> - The path to a Conda environment (as `conda:///...`)
> - The path to a virtual environment (as `venv:///...`)
> - The path to a python executable (as `python:///...`)
>
> Note that when not using an archive, the provided path must be valid on all nodes in the cluster.

The archived environments are usually packaged using [`conda-pack`](https://conda.github.io/conda-pack/) or [`venv-pack`](https://jcrist.github.io/venv-pack/).

This is nice because it forces the user to explicitly think about their dependencies, and allows pre-packaging them into archives (instead of every run), as well as the option to pre-store them on HDFS. `dask-yarn` then only needs to think about distributing the archive files (if necessary), and activating the environments.

**Comment by fhoering** [comment]
Thanks @jcrist. 
We also noticed that dynamically creating the virtual environment can create issues and doesn't force the user to explicitly think about the dependencies. 
Currently the default is still to build a conda environment based on the `requirements.txt` but we already have implemented something similar to dask. We kept the default for simplicity but in our own use cases we always inject the prepackaged environment.

It doesn't work with a prefix but we take action based on the file extension. We support [pex](https://pex.readthedocs.io/en/stable/) and conda zip packages (packaged with conda-pack)

```
TFYarnExecutor(
  ..
 pyenv_zip_path="myarchive.zip"
)
```

I close this ticket.

**Comment by fhoering** [comment]
@jcrist Actually maybe pex is also something that could be included in dask somehow.
I have written a blogpost about how we use it. We actually use it the same way with pyspark and tf-yarn. There is also a "dev" mode that allows to upload dynamically editable packages each time in addition to the prepackaged conda/venv/pex environment.
https://medium.com/criteo-labs/packaging-code-with-pex-a-pyspark-example-9057f9f144f3
